markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Tim Jahn
url: http://timjahn.com
description: A dude
twitter: timjahn
gravatar_url: http://www.gravatar.com/avatar/78584e4bac5acdddaa3f4d1e2763f9ba
