markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Tim Jahn
url: http://timjahn.com
description: A dude
twitter: timjahn
gravatar: http://www.gravatar.com/avatar/6b832922743cd34c9cc2780365272dcf
