markdown: rdiscount
pygments: true
permalink: /:title.html
auto: true
rdiscount:
  extensions: [smart]

name: Tim Jahn
url: http://timjahn.com
description: The personal site of Tim Jahn, co-founder of matchist.
twitter: timjahn
gravatar_url: http://www.gravatar.com/avatar/6b832922743cd34c9cc2780365272dcf
